spring:
  application:
    name: gapsi-products-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    schema: public
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true

springdoc:
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html